default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

development:
  <<: *default
  host: db
  database: myapp_development
  password: password

test:
  <<: *default
  host: db
  database: myapp_test
  password: password

# AWSの設定
# production:
#   <<: *default
#   database: myapp_production
#   url: <%= Rails.application.credentials.production.database_url %>

production:
  <<: *default
  username: <%= Rails.application.credentials.planetscale&.fetch(:username) %>
  password: <%= Rails.application.credentials.planetscale&.fetch(:password) %>
  database: <%= Rails.application.credentials.planetscale&.fetch(:database) %>
  host: <%= Rails.application.credentials.planetscale&.fetch(:host) %>
  ssl_mode: verify_identity
  sslca: '/etc/ssl/certs/ca-certificates.crt'
